### ISSUE TITLE
Several proc freq and proc means options not highlighted

### ISSUE THREAD

**Issue by andres-s** [rpardee/sas#11]
Here `nopercent` should be highlighted the same way as the other two options
```sas
proc freq order=freq data=mydata;
    tables myvar / nocol nopercent nocum;
run;
```

The percentile options below should also be similarly highlighted
```sas
proc means data=mydata n mean std min max p1 p5 p10 p25 median p75 p90 p95 p99;
    var myvar;
run;
```

**Edit**:
If this issue is fixed the code blocks above will change. When the issue was opened they looked like this:

![image](https://cloud.githubusercontent.com/assets/3961287/5829226/0640a628-a163-11e4-8e1d-d72ace216273.png)

and

![image](https://cloud.githubusercontent.com/assets/3961287/5829231/0dc6a92e-a163-11e4-8ce3-f2482dff22be.png)

**Comment by rpardee** [comment]
Aye, that's legit--thanks much for the report.

**Comment by rpardee** [comment]
Ack, sorry--didn't mean to close this.

**Comment by rpardee** [comment]
Alright--latest push should fix this.  Thanks for the report!

I guess I should send the linguist folks a pull request?  Not sure how to make my updates effective on the site...

**Comment by andres-s** [comment]
Thanks for the fix.

Judging by the last paragraph in the [Linguist](https://github.com/github/linguist) readme, the Linguist maintainers need to run `git submodule update --remote`. Maybe leave it for a couple of weeks and if the grammar isn't updated, create an issue in the Linguist repo.

**Comment by rpardee** [comment]
Will do--thanks!
