### ISSUE TITLE
sql snippet adds proc in front of SQL

### ISSUE THREAD

**Issue by TorbenChristensen** [rpardee/sas#13]
giving the result:

proc proc sql....
easy to modify in the sql snippit

**Comment by rpardee** [comment]
Aye, that's true--my habit is to just type the 'sql' trigger when I want a proc sql block.

**Comment by TorbenChristensen** [comment]
If you change your current  sql.sublime_snippet to this one the sql code completion is ok.

**Comment by TorbenChristensen** [comment]
however then the sql code snippet does not work :-(

**Comment by rpardee** [comment]
Tempted to close this as not-a-bug.  Is good?
