### ISSUE TITLE
Proposal: a dataset explorer

### ISSUE THREAD

**Issue by ngr-t** [rpardee/sas#23]
I think it is nice for this package to have a function to list datasets in libraries and see their contents.
In my image, this function works as below:

1. We have pairs of libname and its corresponding path on a setting file in advance.
2. List the names of libraries in a menu and we choose one of them.
3. List the names of datasets in the chosen library and we choose the one to see the contents.
4. (Optionally) Decide the start and the end of the observations to be read.
5. Show them in a buffer.

How do everyone think about it? Thank you.

**Comment by rpardee** [comment]
I must confess this idea does not excite me.  For me one of the main benefits of sublime is how light-weight and clean the interface is.  In my opinion the SAS Viewer (the classic one) handles this functionality very well.  (I've also got a separate script (see attached) that puts an item on windows explorer's 'Send To' menu that produces a quick PROC CONTENTS & proc print obs = 20 output for datasets too large for the viewer.)
[QuickContentsHTML.wsf.txt](https://github.com/rpardee/sas/files/172872/QuickContentsHTML.wsf.txt)

So for my part, I would not use this feature if it were added.

**Comment by ngr-t** [comment]
Understood.
Anyway I will make the thing like I proposed, but now I don't think it has to be a part of this package.
Simply I dislike to switch back and forth among windows and thought there are several people of the same idea.
Your script is a good suggestion for me, thanks.
