### ISSUE TITLE
Package Control 

### ISSUE THREAD

**Issue by bobfourie** [rpardee/sas#25]
Thnx for the package, it's very helpful. You have on your to do list to add it to Package Control, I have created a json snip to help you, please change as needed.
`		"name": "SAS",
		"details": "https://github.com/rpardee/sas",
		"labels": ["language syntax"],
		"releases": [
		{
			"sublime_text": ">=3000",
			"tags": true
		}
		]
		},`
Just fork package_control_channel on github, make the change in the file: package_control_channel/repository/s.json, the snip has to go just before SASS in the package_control_channel.Submit a Pull Request.

I did check it with ChannelRepositoryTools: Test Default Channel command it showed it worked ok
https://packagecontrol.io/docs/submitting_a_package

**Comment by rpardee** [comment]
Wonderful--thank you!  I shall give that a whirl.

**Comment by rpardee** [comment]
All righty--I have submitted [a pull request](https://github.com/wbond/package_control_channel/pull/5571).  Let's see if it works.

**Comment by bobfourie** [comment]
Thank you so much, this will be a great time saver
I did updated the snippet after I posted it to conform more to the general way that SASS have done it. Sorry to ask this, could you please close the request and use the updated one in the original post. I removed the platform because the syntax can be used in linux and osx, the build can also be done in linux. I have also added the label: "language syntax"

https://help.github.com/articles/closing-a-pull-request/

**Comment by FriedEgg** [comment]
While the SAS Institute does not offer a version of their Base SAS product for OSX, there are alternatives, which use the Language of SAS, such as that from World Programming which do support OSX.

**Comment by rpardee** [comment]
Okay then--taking out the platforms key.

**Comment by rpardee** [comment]
Mission accomplished.  Many thanks @bobfourie for getting this ball rolling!
![image](https://cloud.githubusercontent.com/assets/26327/16196173/cc4e11e0-36b1-11e6-9c28-c776a8295487.png)
