### ISSUE TITLE
syntax highlighting breaks with macro calls in quotes

### ISSUE THREAD

**Issue by travisflemming** [rpardee/sas#26]
The highlighting for quoted strings does not end correctly when using a macro call inside the quotes. I attached a screenshot to show an example.

![broken_syntax](https://cloud.githubusercontent.com/assets/6929222/16988845/ccd79a3a-4e5f-11e6-9650-05f95ab41bf0.png)

**Comment by rpardee** [comment]
Ah, good catch--thanks.

Looks like any paren or percent char inside a date constant style string will throw off the highlighting.

**Comment by FriedEgg** [comment]
I removed a bunch of the over-complexity and strictness with the definition of constants and quoted strings, but, that should be the most robust fix for this...  The 'catchall' that was defined was pretty poor, as well.


![image](https://cloud.githubusercontent.com/assets/165806/17003172/a91d98be-4e9c-11e6-8d53-9af0e32eee5a.png)

**Comment by rpardee** [comment]
Lovely!  Thank you @FriedEgg!
