### ISSUE TITLE
Proposal: partial code submission to build system

### ISSUE THREAD

**Issue by adam-garcia** [rpardee/sas#27]
One feature that I use frequently while developing SAS in the Editor is partial submission by code selection (helpful for debugging/testing). Would this type of feature be available to the build system?

**Comment by rpardee** [comment]
It seems like this should be possible by e.g., writing selected code off to a temp file & batch-submitting that, but I expect it would be a pretty big PITA to pull off.  One big difficulty is--as currently implemented anyway, there is no persistent SAS process hanging out in the background maintaining state (like defined libnames, macro vars, work datasets, etc.) that can pick up where your last-run code left off.  So for it to work, you'd either have to require that the user select enough code to fully reproduce the proper environment every time, or write some kind of environmental code detector that can figure out what it should run (e.g., run the proc freq that the user has selected right now, *and* the libnames that define the lib referred to *and* the prior SQL code that creates the dset getting FREQed, etc.).  At that point you're not saving much run-time.

I'm not sure how easy it would be to keep a persistent slave SAS process that could maintain such state, to which you could feed bits of code.  On windows you could maybe achieve the required inter-process communication via COM (?maybe?) but I have no clue how you'd do it on linux, say.

Sooo--all this is to say that I am not very tempted to try this, personally.  I'm happy to get pull requests w/already-done implementations though. ;-)

Sorry not to be more accommodating.
