### ISSUE TITLE
Cannot add "-config" to SAS args in SAS_Package.sublime-settings on Windows

### ISSUE THREAD

**Issue by popwar2** [rpardee/sas#28]
When the argument -config "C:\\Program Files\\SASHome\\SASFoundation\\9.4\\sasv9.cfg" is added to SAS_Package.sublime-settings it is passed to SAS as a string literal and SAS is unable to find the config file. It's not possible to save the string as -config "C:\Program Files\SASHome\SASFoundation\9.4\sasv9.cfg" as sublime throw an error saying that the string has an error in it. It would be incredibly helpful to add -config and -sasautos to the 'sas-args' section so that code can be written relying on other macros. Escaping the quotes, \", and backslashes does not work either.

Examples of args in sasv9.cfg:
-sasautos ("C:\projects\sas\macro_dir_1", "C:\projects\sas\macro_dir_2")

Examples of args in SAS_Package.sublime-settings:
-config "C:\projects\sas\sasv9.cfg"
-sasautos ("C:\projects\sas\macro_dir_1", "C:\projects\sas\macro_dir_2")

**Comment by rpardee** [comment]
Confirmed.  I'll see if I can fix this.  I'm guessing there's going to be an upper limit on the total length of the call that python's subprocess.call (or the underlying OS) can handle, but let's see if we can give you enough rope to hang yourself with. ;-)

Thanks for the report!

**Comment by popwar2** [comment]
Thanks! I was looking at the python and it seems like the easiest thing would be to add another element to settings file that is similar to sas-path.

**Comment by rpardee** [comment]
Give this a whirl & let me know how it works for you.

**Comment by popwar2** [comment]
Looks great. Thank you for adding that.
