### ISSUE TITLE
Macro variables not defined

### ISSUE THREAD

**Issue by aminaredab** [rpardee/sas#39]
Hi!

I am not able to call a macro variable that I have defined in a different sas program. On the log I get the following: ''WARNING: Apparent symbolic reference <macro_name> not resolved''. Typically in SAS I am able to use all macro variables that I have defined in the current session.

Is there a way to fix this?

**Comment by rpardee** [comment]
Huh, that's a good one.  I have not seen that behavior.

Are you explicitly %include'ing the program where the macro vars are defined?  With sublime (as with batch-mode SAS generally) your session only lives for as long as the dialog thing stays up--this guy:

![image](https://user-images.githubusercontent.com/26327/47324549-28162f80-d615-11e8-889e-a0d33aa981f0.png)

So you've got to define all your libnames, macros, vars etc. anew each time.

Apologies if this is stuff you already know...

**Comment by rpardee** [comment]
Closing this due to nonresponse.
