### ISSUE TITLE
Macro comment is not recognized by new syntax definition

### ISSUE THREAD

**Issue by rajwanur** [rpardee/sas#40]
I believe there is SAS comment type which is called SAS macro comments, starts with `%*` and ends with a semicolon `;` New syntax definition does not include definition for this and thus this type of comments is not get recognized. 

Here is an example, where line 10 does not gets recognized as comment. 
![image](https://user-images.githubusercontent.com/2075789/124558831-d497ae80-de5c-11eb-9067-625a7d8b4b45.png)

How it look in SAS editor
![image](https://user-images.githubusercontent.com/2075789/124559178-3eb05380-de5d-11eb-9908-b30007c9bd19.png)

An update in following block should solve this issue. 
https://github.com/rpardee/sas/blob/678d9446f93f62b59399206841bf6e11c881606f/syntaxes/SAS%20Program.sublime-syntax#L202

Thank you

**Comment by rpardee** [comment]
Ooh--right you are--many thanks for reporting!
