### ISSUE TITLE
Syntax highlighting bug for comments after parentheses.

### ISSUE THREAD

**Issue by gdlind** [rpardee/sas#41]
I think this is a syntax highlighting bug:

When defining a variable in a data step, the multiplication sign (*) invokes comment syntax highlighting ONLY after a closed parenthesis (when using a function, for example).

For example, when typing:

var = lag1(var2) * var3;

Everything following the "*" is grayed out as a comment. 

This does not impact the running of the code, just the syntax highlighting.

**Comment by rpardee** [comment]
ach, right you are. Looking into this. Thanks for the report!

**Comment by rpardee** [comment]
Latest version should greatly improve this behavior--let me know how it looks on your end.

**Comment by rpardee** [comment]
Lovely--thanks very much for the report!
